[pdc]
Chris-SQL-AD ansible_host='10.15.76.36' ansible_port='5986' ansible_user='administrator' ansible_password='Zaq!2wsX' server_state='running'

[dc]
Chris-SQL-Node2 ansible_host='10.15.76.12' ansible_port='5986' ansible_user='administrator' ansible_password='Zaq!2wsX' server_state='running'
Chris-SQL-Node1 ansible_host='10.15.76.22' ansible_port='5986' ansible_user='administrator' ansible_password='Zaq!2wsX' server_state='running'


[pdc:vars]
app360_min_cpu=2
app360_min_mem=2
app360_min_count=1
app360_max_count=1
app360_os=windows
ansible_winrm_server_cert_validation=ignore
ansible_connection=winrm
ansible_winrm_scheme=https
ansible_winrm_transport=credssp

[dc:vars]
app360_min_cpu=2
app360_min_mem=2
app360_min_count=1
app360_os=windows
ansible_winrm_server_cert_validation=ignore
ansible_connection=winrm
ansible_winrm_scheme=https
ansible_winrm_transport=credssp
